spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    hikari:
      pool-name: ${DB_POOL_NAME}
      maximum-pool-size: ${DB_POOL_MAX_SIZE}
      minimum-idle: ${DB_POOL_MIN_IDLE}
      connection-timeout: ${DB_POOL_CONNECTION_TIMEOUT}
      idle-timeout: ${DB_POOL_IDLE_TIMEOUT}
      max-lifetime: ${DB_POOL_MAX_LIFETIME}

  jpa:
    database-platform: ${JPA_DIALECT}
    show-sql: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: ${JPA_BATCH_SIZE}
        order_inserts: true
        order_updates: true