server:
  forward-headers-strategy: native

spring:
  mvc:
    apiversion:
      use:
        header: ${API_VERSION_HEADER}
      supported: ${API_VERSION_SUPPORTED}
      default: ${API_VERSION_DEFAULT}
