create extension if not exists pg_cron;
create schema documento;
create schema pessoas;
create schema usuarios;
create schema vinculos;
create schema enderecos;
create schema imoveis;
create schema catalogo;
create schema vistorias;
create schema rotinas;
